import { readFileSync,writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { loadEnvFile } from 'node:process';
import { execFileSync } from 'node:child_process';
import { SolanaRpc,type ChainTransaction } from '../../src/funding/solana/rpc.js';
import { decodeTransaction } from '../../src/funding/solana/wire.js';
loadEnvFile(process.argv[2]??'C:/Dev/token2049-origins/.env.local');
const path='docs/work/SOLANA_LIVE.json',report=JSON.parse(readFileSync(path,'utf8'));
if(report.outcome!=='PASS')throw new Error('existing successful live evidence required');
const rpc=new SolanaRpc(process.env.SOLANA_RPC_URL!);await rpc.assertNetwork();
const chain=await rpc.call<ChainTransaction>('getTransaction',[report.chain.signature,{commitment:'finalized',encoding:'base64',maxSupportedTransactionVersion:0}]);
if(!chain.meta||chain.meta.err)throw new Error('historical chain evidence missing');
const t=decodeTransaction(chain.transaction[0]);
if(t.signature!==report.chain.signature||t.amount!==report.chain.amountBaseUnits||t.mint!==process.env.SOLANA_USDC_MINT||t.destination!==process.env.SOLANA_TREASURY_TOKEN_ACCOUNT||t.source!==process.env.SOLANA_PAYER_TOKEN_ACCOUNT||t.memo!==report.chain.memo)throw new Error('historical evidence binding mismatch');
const balances=(key:string,owner:string)=>{const i=t.accounts.indexOf(key),pre=chain.meta!.preTokenBalances.find(b=>b.accountIndex===i),post=chain.meta!.postTokenBalances.find(b=>b.accountIndex===i);if(!pre||!post||[pre,post].some(b=>b.mint!==t.mint||b.owner!==owner||b.uiTokenAmount.decimals!==6))throw new Error('historical balance identity mismatch');return {before:pre.uiTokenAmount.amount,after:post.uiTokenAmount.amount};};
const source=balances(t.source,process.env.SOLANA_PAYER_ADDRESS!),destination=balances(t.destination,process.env.SOLANA_TREASURY_ADDRESS!);
if(BigInt(source.before)-BigInt(source.after)!==BigInt(t.amount)||BigInt(destination.after)-BigInt(destination.before)!==BigInt(t.amount))throw new Error('historical exact delta mismatch');
report.chain.source=source;report.chain.destination=destination;report.recheckedAt=new Date().toISOString();report.sourceBaseSha=execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim();
report.executionDependencies={solanaKit:'6.1.0',x402Svm:'2.26.0'};
report.recheckDependencies={solanaKit:JSON.parse(readFileSync('node_modules/@solana/kit/package.json','utf8')).version,x402Svm:JSON.parse(readFileSync('node_modules/@x402/svm/package.json','utf8')).version,node:process.version};
const files=['package.json','package-lock.json','src/funding/solana/adapter.ts','src/funding/solana/config.ts','src/funding/solana/rpc.ts','src/funding/solana/wire.ts','clients/solana/config.ts','clients/solana/facilitator.ts','clients/solana/ledger.ts','clients/solana/pay.ts','clients/solana/policy.ts','clients/solana/signer.ts'];
const hash=createHash('sha256');for(const file of files){hash.update(file+'\0');hash.update(readFileSync(file));}report.recheckedImplementationSha256=hash.digest('hex');
writeFileSync(path,JSON.stringify(report,null,2));console.log(JSON.stringify({outcome:'PASS',recheckedAt:report.recheckedAt,signature:t.signature,source,destination,implementationSha256:report.recheckedImplementationSha256}));
