/**
 * Generate a disposable Preprod payer wallet.
 *
 *   PAYER_CARDANO_MNEMONIC_FILE=./wallets/payer.mnemonic npx tsx clients/payer/wallet-generate.ts
 *
 * - The BIP39 mnemonic is generated by the Evolution SDK and written ONLY to the file at
 *   PAYER_CARDANO_MNEMONIC_FILE, created exclusively (refuses to overwrite) with mode 0600.
 * - stdout gets the bech32 address and faucet links, nothing else. The mnemonic is never printed, never logged.
 * - Back the file up out of band if the wallet will ever hold more than test tokens (it should not).
 */
import { existsSync, closeSync, mkdirSync, openSync, unlinkSync, writeSync } from 'node:fs';
import { dirname } from 'node:path';
import { pathToFileURL } from 'node:url';
import { PrivateKey } from '@evolution-sdk/evolution';
import { toClientCardanoSigner } from '@x402/cardano';

import { payerLedgerPath } from './config.js';
import { PayerLedger } from './ledger.js';

export const FAUCET_LINKS = {
  tADA: 'https://docs.cardano.org/cardano-testnets/tools/faucet',
  tUSDM: 'https://tusdm.moneta.global',
} as const;

export interface Out {
  write(chunk: string): unknown;
}

export class WalletExistsError extends Error {
  constructor() {
    super('mnemonic file already exists; refusing to overwrite');
  }
}

export function generateWallet(env: NodeJS.ProcessEnv, out: Out): { address: string } {
  const file = String(env.PAYER_CARDANO_MNEMONIC_FILE ?? '').trim();
  if (!file) throw new Error('PAYER_CARDANO_MNEMONIC_FILE is required');
  if (String(env.PAYER_CARDANO_NETWORK ?? 'cardano:preprod').trim() !== 'cardano:preprod') {
    throw new Error('PAYER_CARDANO_NETWORK must be cardano:preprod');
  }

  const ledgerFile = payerLedgerPath(env.PAYER_LEDGER_FILE);
  if (existsSync(file)) {
    if (!existsSync(ledgerFile)) throw new Error('payer wallet exists but ledger is missing; operator reconciliation required');
    throw new WalletExistsError();
  }
  if (existsSync(ledgerFile)) throw new Error('payer ledger already exists; refusing to reset history');
  const mnemonic = PrivateKey.generateMnemonic(256);
  // The address is derived locally by the same SDK path the signer uses; no network call, so the
  // provider values are placeholders and are never used.
  const address = toClientCardanoSigner({
    mnemonic,
    network: 'cardano:preprod',
    provider: { blockfrost: { baseUrl: 'https://cardano-preprod.blockfrost.io/api/v0', projectId: 'offline' } },
  }).getAddress();

  mkdirSync(dirname(file), { recursive: true });
  let fd: number;
  try {
    // 'wx' = create exclusively: an existing wallet file is never touched.
    fd = openSync(file, 'wx', 0o600);
  } catch (e) {
    if ((e as NodeJS.ErrnoException).code === 'EEXIST') throw new WalletExistsError();
    throw new Error('cannot create mnemonic file');
  }
  try {
    writeSync(fd, `${mnemonic}\n`);
  } catch {
    closeSync(fd);
    try {
      unlinkSync(file); // never leave a half-written wallet behind
    } catch {
      /* ignore */
    }
    throw new Error('cannot write mnemonic file');
  }
  closeSync(fd);

  // If ledger creation fails, the new wallet remains and payment refuses until reconciled.
  PayerLedger.initialize(ledgerFile);

  out.write(`Payer address (cardano:preprod):\n${address}\n\n`);
  out.write(`Fund it with test tokens only:\n  tADA  ${FAUCET_LINKS.tADA}\n  tUSDM ${FAUCET_LINKS.tUSDM}\n`);
  out.write('\nThe recovery phrase was written to the configured mnemonic file (not shown). Keep that file private.\n');
  return { address };
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  try {
    generateWallet(process.env, process.stdout);
  } catch (e) {
    process.stderr.write(`${e instanceof Error ? e.message : 'wallet generation failed'}\n`);
    process.exitCode = 1;
  }
}
